# Usa uma imagem base leve do Python
FROM python:3.11-slim

# Define o diretório de trabalho
WORKDIR /app

# Copia apenas o requirements.txt primeiro (boa prática para cache)
COPY requirements.txt .

# Instala as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante do projeto
COPY . .

# Define o comando padrão (pode ser alterado)
CMD ["python", "simulateFiveUser.py"]